backend/apps/about/urls.py
from django.urls import path
from .views import index

app_name = 'about'

urlpatterns = [
    path('', index, name="index"),
]

backend/apps/contacts/urls.py
from django.urls import path
from .views import ContactFormView

app_name = 'contacts'

urlpatterns = [
    path('', ContactFormView.as_view(), name="index"),
]

backend/apps/delivery/urls.py
from django.urls import path
from .views import index

app_name = 'delivery'

urlpatterns = [
    path('', index, name="index"),
]

backend/apps/products/urls.py
from django.urls import path
from .views import ProductDetailView

app_name = 'products'

urlpatterns = [
    path('<slug:slug>/', ProductDetailView.as_view(), name="detail"),
]

backend/backend/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap

from .sitemaps import StaticViewSitemap, ProductsSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "products": ProductsSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
    path(
        'sitemap.xml',
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

urlpatterns += i18n_patterns(
    path('', include('apps.home.urls')), 
    path('products/', include('apps.products.urls')), 
    path('delivery/', include('apps.delivery.urls')),
    path('contacts/', include('apps.contacts.urls')),
    path('about/', include('apps.about.urls')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

backend/templates/layout/_partials/header.html
{% load static %}
{% load i18n %}
{% load project_extras %}

{% contact_data as contact_data %}
<header id="js-header"
        class="u-header u-header--sticky-top--lg u-header--toggle-section--lg u-header--change-appearance"
        data-header-fix-moment="200"
        data-header-fix-effect="slide">
    <div class="text-center text-lg-left u-header__section u-header__section--hidden u-header__section--light g-bg-white g-brd-bottom g-brd-gray-light-v4 g-py-10">
        <div class="container">
            <div class="row flex-lg-row align-items-center justify-content-lg-start">
                <div class="col-6 col-sm-3 col-lg-2">
                    <!-- Logo -->
                    <a href="{% url 'home' %}" class="navbar-brand"
                       data-type="static">
                        <img class="img-fluid g-width-150" src="{% static 'img/logo/glana_logo.png' %}" alt="Logo">
                    </a>
                    <!-- End Logo -->
                </div>

                <div class="col-6 col-sm-9 col-lg-10">
                    <div class="row">
                        <div class="col-sm g-brd-right--sm g-brd-gray-light-v4">
                            <div class="g-py-10--lg g-pl-10--lg">
                                <span class="g-valign-middle g-font-size-18 g-color-primary g-mr-5"><i class="fa fa-phone"></i></span>
                                <span class="text-uppercase g-font-size-13">{% trans 'Телефон' %}</span>
                                <strong class="d-block">
                                    <a class="g-color-main g-font-size-16"
                                       href="tel:{{ contact_data.phone }}">{{ contact_data.phone }}</a>
                                </strong>
                            </div>
                        </div>

                        <div class="col-sm g-hidden-lg-down g-brd-right--sm g-brd-gray-light-v4">
                            <div class="g-pa-10--lg">
                                <span class="g-valign-middle g-font-size-18 g-color-primary g-mr-5"><i class="fa fa-pencil"></i></span>
                                <span class="text-uppercase g-font-size-13">{% trans 'Напишіть нам у месенжер' %}</span>

                                <ul class="list-inline g-pl-20 mb-0">
                                    <li class="list-inline-item g-valign-middle">
                                        <a href="https://t.me/{{ contact_data.phone|clear_number }}" target="_blank">
                                            <img class="g-height-30" src="{% static 'img/icons/icons8-telegram.svg' %}" alt="">
                                        </a>
                                    </li>
                                    <li class="list-inline-item g-valign-middle">
                                        <a href="viber://chat?number={{ contact_data.phone|clear_number }}">
                                            <img class="g-height-30" src="{% static 'img/icons/icons8-viber.svg' %}" alt="">
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="col-sm g-hidden-lg-down g-brd-right--sm g-brd-gray-light-v4">
                            <div class="g-pa-10--lg">
                                <span class="g-valign-middle g-font-size-18 g-color-primary g-mr-5"><i class="fa fa-camera-retro"></i></span>
                                <span class="text-uppercase g-font-size-13">{% trans 'Ми у соцмережах' %}</span>
                                <ul class="list-inline g-pl-20 mb-0">
                                    {% if contact_data.instagram_link %}
                                        <li class="list-inline-item g-valign-middle">
                                            <a class="d-block u-icon-v3 u-icon-size--xs g-rounded-50x g-bg-gray-light-v4 g-color-gray-dark-v4 g-bg-primary--hover g-color-white--hover"
                                               href="{{ contact_data.instagram_link }}"><i class="fa fa-instagram "></i></a>
                                        </li>
                                    {% endif %}

                                    {% if contact_data.fb_link %}
                                        <li class="list-inline-item g-valign-middle">
                                            <a class="d-block u-icon-v3 u-icon-size--xs g-rounded-50x g-bg-gray-light-v4 g-color-gray-dark-v4 g-bg-primary--hover g-color-white--hover"
                                               href="{{ contact_data.fb_link }}"><i
                                                    class="fa fa-facebook g-font-size-default"></i></a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>

                        {% include 'home/_partials/languages.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="u-header__section u-header__section--dark g-bg-gray-dark-v1 g-py-15"
         data-header-fix-moment-classes="u-shadow-v18">
        <nav class="js-mega-menu navbar navbar-expand-lg  hs-menu-initialized hs-menu-horizontal py-0">
            <div class="container">
                <!-- Navigation -->
                <div class="collapse navbar-collapse align-items-center flex-sm-row g-pt-10 g-pt-5--lg" id="navBar">
                    <ul class="navbar-nav text-uppercase g-font-weight-700 mr-auto">
                        <li class="nav-item g-mr-15--lg g-mb-7 g-mb-0--lg">
                            <a href="{% url 'home' %}" class="nav-link g-color-primary--hover p-0">{% trans 'Головна' %}</a>
                        </li>

                        <li class="hs-has-mega-menu nav-item g-mx-15--lg g-mb-7 g-mb-0--lg {% if 'products/' in request.path %}active{% endif %}"
                            data-animation-in="fadeIn"
                            data-animation-out="fadeOut"
                            data-position="right">
                            <a id="mega-menu-label-3" class="nav-link g-color-primary--hover p-0" href="#!" aria-haspopup="true"
                               aria-expanded="false">{% trans 'Продукція' %}
                                <i class="hs-icon hs-icon-arrow-bottom g-font-size-11 g-ml-7"></i>
                            </a>

                            {% product_types as product_types %}

                            <!-- Mega Menu -->
                            <div class="w-100 hs-mega-menu u-shadow-v11 g-text-transform-none g-font-weight-400 g-brd-top g-brd-primary g-brd-top-2 g-bg-white g-pa-30 g-mt-13 g-mt-7--lg--scrolling"
                                 aria-labelledby="mega-menu-label-3">
                                <div class="row">
                                    {% for type in product_types %}
                                        <div class="col-12 g-mb-15">
                                            <h4 class="h5 text-uppercase g-font-weight-600">{{ type.title }}</h4>

                                            <div class="row">
                                                {% for product in type.products %}
                                                    <div class="col-12 col-lg-3 g-mb-5">
                                                        <a class="{% if product.slug in request.path %}g-color-primary{% else %}g-color-main{% endif %} g-font-size-14"
                                                           href="{% url 'products:detail' slug=product.slug %}"
                                                        >{{ product.title }}</a>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <!-- End Mega Menu -->
                        </li>

                        <li class="nav-item g-mx-15--lg g-mb-7 g-mb-0--lg {% if 'about/' in request.path %}active{% endif %}">
                            <a href="{% url 'about:index' %}" 
                               class="nav-link g-color-primary--hover p-0">{% trans 'Про нас' %}</a>
                        </li>

                        <li class="nav-item g-mx-15--lg g-mb-7 g-mb-0--lg {% if 'delivery/' in request.path %}active{% endif %}">
                            <a href="{% url 'delivery:index' %}" 
                               class="nav-link g-color-primary--hover p-0">{% trans 'Доставка' %}</a>
                        </li>

                        <li class="nav-item g-mx-15--lg g-mb-7 g-mb-0--lg {% if 'contacts/' in request.path %}active{% endif %}">
                            <a href="{% url 'contacts:index' %}"
                               class="nav-link g-color-primary--hover p-0">{% trans 'Контакти' %}</a>
                        </li>

                    </ul>
                </div>
                <!-- End Navigation -->

                <div class="g-hidden-md-down text-uppercase g-valign-middle">
                    <a href="#price-request"
                       data-modal-target="#price-request"
                       data-modal-effect="fadein"
                       class="btn btn-md text-uppercase u-btn-primary g-font-weight-700 g-font-size-12 g-brd-none g-rounded-4 g-py-12 g-px-15">{% trans 'Замовити розрахунок' %}</a>
                </div>

                <!-- Responsive Toggle Button -->
                <button class="navbar-toggler btn g-pos-rel g-line-height-1 g-brd-none g-pa-0 g-pos-abs g-top-minus-8 g-right-0" type="button"
                        aria-label="Toggle navigation"
                        aria-expanded="false"
                        aria-controls="navBar"
                        data-toggle="collapse"
                        data-target="#navBar">
                <span class="hamburger hamburger--slider">
                  <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                  </span>
                </span>
                </button>
                <!-- End Responsive Toggle Button -->
            </div>
        </nav>
    </div>
</header>

backend/templates/layout/_partials/order_modal_form.html
{% load i18n %}

<div id="price-request" class="text-left g-max-width-600 g-bg-white g-overflow-y-auto g-pa-20" style="display: none;">
    <button type="button" class="close" onclick="Custombox.modal.close();">
        <i class="hs-icon hs-icon-close"></i>
    </button>
    <h4 class="g-mb-20">{% trans "Замовити розрахунок" %}</h4>
    <p>{% trans "Будь ласка, заповніть форму нижче для уточнення деталей" %}:</p>

    <form id="promo-form-modal" method="post" enctype="multipart/form-data" action="/order">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <div class="form-group g-mb-10 g-mb-20--md">
                    <input name="username"
                           class="form-control g-brd-gray-light-v5 g-bg-gray-light-v5 g-bg-gray-light-v5--focus g-px-10 g-py-12"
                           placeholder="{% trans "Ім'я" %}"
                           type="text">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group g-mb-10 g-mb-20--md">
                    <input name="phone"
                           class="form-control g-theme-color-gray-light-v10 g-placeholder-inherit g-brd-gray-light-v5 g-bg-gray-light-v5 g-bg-gray-light-v5--focus g-px-10 g-py-12"
                           placeholder="{% trans "Телефон" %}"
                           type="tel">
                </div>
            </div>
        </div>

        <div class="form-group g-mb-10 g-mb-20--md">
            <input name="email"
                   data-error-class="u-has-error-v1"
                   class="form-control g-theme-color-gray-light-v10 g-placeholder-inherit g-brd-gray-light-v5 g-bg-gray-light-v5 g-bg-gray-light-v5--focus g-px-10 g-py-12"
                   type="email"
                   placeholder="E-Mail*">
        </div>

        <div class="form-group g-mb-10 g-mb-20--md">
            <textarea name="message"
                      data-error-class="u-has-error-v1"
                      class="form-control g-theme-color-gray-light-v10 g-placeholder-inherit g-brd-gray-light-v5 g-bg-gray-light-v5 g-bg-gray-light-v5--focus g-px-10 g-py-12 g-resize-none"
                      rows="3"
                      placeholder="{% trans "Повідомлення" %}*"></textarea>
        </div>

        <!-- File Input -->
        <div class="form-group g-mb-10 g-mb-20--md">
            <div class="input-group u-file-attach-v1 g-brd-gray-light-v2">
                <input class="form-control g-theme-color-gray-light-v10 g-placeholder-inherit g-brd-gray-light-v5 g-bg-gray-light-v5 g-bg-gray-light-v5--focus g-px-10 g-py-12"
                       placeholder="Выбрать файл (до 5 Мб)"
                       readonly=""
                       type="text">

                <div class="input-group-append">
                    <button class="btn btn-md u-btn-primary rounded-0" type="submit">{% trans "Огляд" %}</button>
                    <input name="file"
                           type="file"
                           data-error-class="u-has-error-v1">
                </div>
            </div>
        </div>
        <!-- End File Input -->

        <button class="btn btn-md btn-block text-uppercase u-btn-primary g-font-weight-700 g-font-size-12 g-brd-none g-rounded-4 g-py-12 g-px-15"
                type="submit">{% trans "Відправити" %}</button>
    </form>

    <!-- Teal Alert -->
    <div id="promo-form-success" class="alert fade show g-bg-teal g-color-white rounded-0" role="alert" style="display: none">
        <div class="media">
            <span class="d-flex g-mr-10 g-mt-5">
              <i class="fa fa-check g-font-size-25"></i>
            </span>
            <span class="media-body align-self-center">
              {% blocktrans %}<strong>Дякуємо!</strong> Ваше повідомлення було відправлене. Найближчим часом менеджер зв'яжеться з вами.{% endblocktrans %}
            </span>
        </div>
    </div>
    <!-- End Teal Alert -->
</div>